{
 "title": "Proyecto 2 - Monitor de Contenedores",
 "panels": [
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "query": "HGET system:latest total_ram" }
   ]
  },
  {
   "title": "RAM en Uso",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "query": "HGET system:latest used_ram" }
   ]
  },
  {
   "title": "RAM Libre",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "query": "HGET system:latest free_ram" }
   ]
  },
  {
   "title": "Uso de RAM (Histórico)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "ZRANGE system:ram:history 0 -1 WITHSCORES"
    }
   ]
  },
  {
   "title": "Contenedores Eliminados",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "ZRANGE containers:history 0 -1 WITHSCORES"
    }
   ]
  },
  {
   "title": "Top 5 Consumo RAM",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "GET top:ram:1; GET top:ram:2; GET top:ram:3; GET top:ram:4; GET top:ram:5"
    }
   ]
  },
  {
   "title": "Top 5 Consumo CPU",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "query": "GET top:cpu:1; GET top:cpu:2; GET top:cpu:3; GET top:cpu:4; GET top:cpu:5"
    }
   ]
  }
 ]
}